// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hitokoto: typeof import('./src/components/Hitokoto.vue')['default']
    Links: typeof import('./src/components/Links.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    MoreContent: typeof import('./src/components/MoreContent.vue')['default']
    Music: typeof import('./src/components/Music.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    Set: typeof import('./src/components/Set.vue')['default']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
    TimeCapsule: typeof import('./src/components/TimeCapsule.vue')['default']
    Weather: typeof import('./src/components/Weather.vue')['default']
  }
}
